import type { Session } from './api.js';

const STALE_INTERNAL_PREFIXES = [
  '<system_instruction>',
  '<environment_context>',
  '<local-command-caveat>',
  '<command-name>',
  '<command-message>',
  'Caveat: The messages below were generated by the user while running local commands.',
  'Respond directly to the user',
  'You are generating a git branch name',
];

export function meaningfulPromptText(value?: string | null): string | null {
  const text = value?.replace(/\r\n/g, '\n').trim();
  if (!text) return null;

  if (STALE_INTERNAL_PREFIXES.some((prefix) => text.startsWith(prefix))) return null;
  return text;
}

export function projectLabel(pwd?: string | null): string {
  const path = pwd?.trim();
  if (!path) return '(no project)';

  const parts = path.split('/').filter(Boolean);
  const workspaces = parts.lastIndexOf('workspaces');
  if (workspaces >= 0 && parts.length > workspaces + 2) {
    return `${parts[workspaces + 1]}/${parts[workspaces + 2]}`;
  }

  return parts.at(-1) ?? path;
}

export function sessionTitle(session: Session): string {
  const prompt = meaningfulPromptText(session.firstPrompt);
  if (prompt) return prompt;

  const project = projectLabel(session.pwd);
  const time = formatShortDate(session.modifiedAt ?? session.createdAt);
  return time ? `${project} · ${time}` : project;
}

export function formatRelativeTime(ts?: number | null): string {
  if (!ts) return '';
  const date = new Date(ts);
  if (!Number.isFinite(date.getTime())) return '';
  const diffMs = ts - Date.now();
  const absMs = Math.abs(diffMs);
  const minute = 60 * 1000;
  const hour = 60 * minute;
  const day = 24 * hour;

  if (absMs < minute) return 'just now';
  if (absMs < hour) return formatRelativeUnit(diffMs, minute, 'minute');
  if (absMs < day) return formatRelativeUnit(diffMs, hour, 'hour');
  if (absMs < 30 * day) return formatRelativeUnit(diffMs, day, 'day');
  return date.toLocaleDateString();
}

function formatRelativeUnit(diffMs: number, unitMs: number, label: string): string {
  const value = Math.round(Math.abs(diffMs) / unitMs);
  const suffix = diffMs < 0 ? 'ago' : 'from now';
  return `${value} ${label}${value === 1 ? '' : 's'} ${suffix}`;
}

export function formatShortDate(ts?: number | null): string {
  if (!ts) return '';
  const date = new Date(ts);
  if (!Number.isFinite(date.getTime())) return '';
  return date.toLocaleString(undefined, {
    month: 'short',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  });
}

export function formatFullTime(ts?: number | null): string {
  if (!ts) return '';
  const date = new Date(ts);
  return Number.isFinite(date.getTime()) ? date.toLocaleString() : '';
}

export function formatDuration(start?: number | null, end?: number | null): string {
  if (!start || !end || end <= start) return '';
  const minute = 60 * 1000;
  const hour = 60 * minute;
  const day = 24 * hour;
  const duration = end - start;

  if (duration < minute) return '<1m';
  if (duration < hour) return `${Math.round(duration / minute)}m`;
  if (duration < day) {
    const hours = Math.floor(duration / hour);
    const minutes = Math.round((duration % hour) / minute);
    return minutes ? `${hours}h ${minutes}m` : `${hours}h`;
  }

  const days = Math.floor(duration / day);
  const hours = Math.round((duration % day) / hour);
  return hours ? `${days}d ${hours}h` : `${days}d`;
}

export function messageCountLabel(count?: number | null): string {
  if (count == null) return '';
  return `${count} message${count === 1 ? '' : 's'}`;
}
