const WRAPPER_TAGS = [
  'system_instruction',
  'environment_context',
  'local-command-caveat',
];

const EMPTY_SLASH_COMMANDS = new Set(['/model', '/exit', '/config']);

const INTERNAL_LINE_PREFIXES = [
  'Caveat: The messages below were generated by the user while running local commands.',
  'Respond directly to the user',
  'You are generating a git branch name',
];

function tagContent(text: string, tag: string): string | undefined {
  const match = text.match(new RegExp(`<${tag}\\b[^>]*>([\\s\\S]*?)<\\/${tag}>`, 'i'));
  return match?.[1]?.trim() || undefined;
}

function removeTagBlocks(text: string, tags: string[]): string {
  let out = text;
  for (const tag of tags) {
    out = out.replace(new RegExp(`\\s*<${tag}\\b[^>]*>[\\s\\S]*?<\\/${tag}>\\s*`, 'gi'), '\n');
  }
  return out;
}

function removeSimpleCommandTags(text: string): string {
  return text
    .replace(/\s*<command-name\b[^>]*>[\s\S]*?<\/command-name>\s*/gi, '\n')
    .replace(/\s*<command-message\b[^>]*>[\s\S]*?<\/command-message>\s*/gi, '\n')
    .replace(/\s*<command-args\b[^>]*>\s*<\/command-args>\s*/gi, '\n');
}

function removeInternalLines(text: string): string {
  return text
    .split('\n')
    .filter((line) => {
      const trimmed = line.trim();
      return !INTERNAL_LINE_PREFIXES.some((prefix) => trimmed.startsWith(prefix));
    })
    .join('\n');
}

function userRequest(text: string): string | undefined {
  const match = text.match(/(?:^|\n)\s*User request:\s*([\s\S]*?)(?:\n\s*\n|$)/i);
  return match?.[1]?.trim() || undefined;
}

function isEmptySlashCommand(text: string): boolean {
  const commandName = tagContent(text, 'command-name')?.toLowerCase();
  const commandMessage = tagContent(text, 'command-message')?.toLowerCase();
  return !!(
    (commandName && EMPTY_SLASH_COMMANDS.has(commandName)) ||
    (commandMessage && EMPTY_SLASH_COMMANDS.has(commandMessage))
  );
}

function compact(text: string, limit: number): string | undefined {
  const cleaned = text
    .replace(/\r\n/g, '\n')
    .replace(/[ \t]+\n/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
  if (!cleaned) return undefined;
  return cleaned.slice(0, limit).trim() || undefined;
}

export function extractMeaningfulPrompt(value?: string | null, limit = 500): string | undefined {
  const text = value?.replace(/\r\n/g, '\n').trim();
  if (!text) return undefined;

  const args = tagContent(text, 'command-args');
  if (args) return compact(args, limit);

  const request = userRequest(text);
  if (request) return compact(request, limit);

  if (isEmptySlashCommand(text)) return undefined;

  const stripped = removeInternalLines(removeSimpleCommandTags(removeTagBlocks(text, WRAPPER_TAGS)));
  return compact(stripped, limit);
}

export function extractFirstMeaningfulPrompt(values: Iterable<string | null | undefined>, limit = 500): string | undefined {
  for (const value of values) {
    const prompt = extractMeaningfulPrompt(value, limit);
    if (prompt) return prompt;
  }
  return undefined;
}
